apiVersion: 1
datasources:
  - name: Kaggle
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: https://www.kaggle.com/api/v1
    jsonData:
      authMethod: basic
      basicAuthUser: ${KAGGLE_USERNAME}
      allowedHosts:
        - www.kaggle.com
        - kaggle.com
    secureJsonData:
      basicAuthPassword: ${KAGGLE_API_KEY}
