global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'web-worker'
    static_configs:
      - targets: ['web-worker:8000', 'background-worker:8001', 'scheduler:8002']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
